"""create initial schema with audit integrity constraints

Revision ID: 7f80855699a8
Revises:
Create Date: 2026-07-18 10:10:58.940334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f80855699a8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creators',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('department_code', sa.String(length=40), nullable=False),
    sa.Column('platform', sa.String(length=40), nullable=False),
    sa.Column('handle', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=300), nullable=True),
    sa.Column('profile_url', sa.Text(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('followers_count', sa.Integer(), nullable=True),
    sa.Column('current_status', sa.String(length=80), nullable=True),
    sa.Column('do_not_contact_status', sa.String(length=40), nullable=False),
    sa.Column('do_not_contact_reason', sa.Text(), nullable=True),
    sa.Column('do_not_contact_requested_at', sa.DateTime(), nullable=True),
    sa.Column('owner_bd', sa.String(length=120), nullable=True),
    sa.Column('recommendation_reason', sa.Text(), nullable=True),
    sa.Column('recommended_product_type', sa.String(length=80), nullable=True),
    sa.Column('recommended_collab_type', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creators_created_at'), 'creators', ['created_at'], unique=False)
    op.create_index(op.f('ix_creators_current_status'), 'creators', ['current_status'], unique=False)
    op.create_index(op.f('ix_creators_department_code'), 'creators', ['department_code'], unique=False)
    op.create_index(op.f('ix_creators_do_not_contact_requested_at'), 'creators', ['do_not_contact_requested_at'], unique=False)
    op.create_index(op.f('ix_creators_do_not_contact_status'), 'creators', ['do_not_contact_status'], unique=False)
    op.create_index(op.f('ix_creators_email'), 'creators', ['email'], unique=False)
    op.create_index(op.f('ix_creators_followers_count'), 'creators', ['followers_count'], unique=False)
    op.create_index(op.f('ix_creators_handle'), 'creators', ['handle'], unique=False)
    op.create_index(op.f('ix_creators_owner_bd'), 'creators', ['owner_bd'], unique=False)
    op.create_index(op.f('ix_creators_platform'), 'creators', ['platform'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('product_type', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('selling_points_json', sa.Text(), nullable=False),
    sa.Column('target_audience', sa.Text(), nullable=True),
    sa.Column('collaboration_requirements', sa.Text(), nullable=True),
    sa.Column('campaign_timeline', sa.Text(), nullable=True),
    sa.Column('campaign_deliverables', sa.Text(), nullable=True),
    sa.Column('budget_guidance', sa.Text(), nullable=True),
    sa.Column('forbidden_claims_json', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_type', name='uq_products_product_type')
    )
    op.create_index(op.f('ix_products_created_at'), 'products', ['created_at'], unique=False)
    op.create_index(op.f('ix_products_is_active'), 'products', ['is_active'], unique=False)
    op.create_index(op.f('ix_products_product_type'), 'products', ['product_type'], unique=False)
    op.create_table('reference_materials',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('reference_key', sa.String(length=120), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=40), nullable=False),
    sa.Column('material_type', sa.String(length=60), nullable=False),
    sa.Column('product_type', sa.String(length=80), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_key', 'version', name='uq_reference_material_version')
    )
    op.create_index('ix_reference_materials_active_scope_product', 'reference_materials', ['is_active', 'scope', 'product_type'], unique=False)
    op.create_index(op.f('ix_reference_materials_created_at'), 'reference_materials', ['created_at'], unique=False)
    op.create_index(op.f('ix_reference_materials_is_active'), 'reference_materials', ['is_active'], unique=False)
    op.create_index(op.f('ix_reference_materials_material_type'), 'reference_materials', ['material_type'], unique=False)
    op.create_index(op.f('ix_reference_materials_product_type'), 'reference_materials', ['product_type'], unique=False)
    op.create_index(op.f('ix_reference_materials_reference_key'), 'reference_materials', ['reference_key'], unique=False)
    op.create_index(op.f('ix_reference_materials_scope'), 'reference_materials', ['scope'], unique=False)
    op.create_table('creator_outreach_events',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('department_code', sa.String(length=40), nullable=False),
    sa.Column('creator_id', sa.String(length=120), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('event_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creator_outreach_events_created_at'), 'creator_outreach_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_creator_outreach_events_creator_id'), 'creator_outreach_events', ['creator_id'], unique=False)
    op.create_index(op.f('ix_creator_outreach_events_department_code'), 'creator_outreach_events', ['department_code'], unique=False)
    op.create_index(op.f('ix_creator_outreach_events_event_at'), 'creator_outreach_events', ['event_at'], unique=False)
    op.create_index(op.f('ix_creator_outreach_events_event_type'), 'creator_outreach_events', ['event_type'], unique=False)
    op.create_table('followup_tasks',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('department_code', sa.String(length=40), nullable=False),
    sa.Column('creator_id', sa.String(length=120), nullable=False),
    sa.Column('owner_user_id', sa.String(length=120), nullable=True),
    sa.Column('task_type', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_followup_tasks_created_at'), 'followup_tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_followup_tasks_creator_id'), 'followup_tasks', ['creator_id'], unique=False)
    op.create_index(op.f('ix_followup_tasks_department_code'), 'followup_tasks', ['department_code'], unique=False)
    op.create_index(op.f('ix_followup_tasks_status'), 'followup_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_followup_tasks_task_type'), 'followup_tasks', ['task_type'], unique=False)
    op.create_table('inbound_replies',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('department_code', sa.String(length=40), nullable=False),
    sa.Column('creator_id', sa.String(length=120), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('channel', sa.String(length=40), nullable=False),
    sa.Column('external_message_id', sa.String(length=320), nullable=False),
    sa.Column('from_email', sa.String(length=320), nullable=False),
    sa.Column('to_email', sa.String(length=1000), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('body_format', sa.String(length=10), nullable=False),
    sa.Column('message_at', sa.DateTime(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('processing_status', sa.String(length=40), nullable=False),
    sa.Column('reply_category', sa.String(length=40), nullable=True),
    sa.Column('classification_confidence', sa.Float(), nullable=True),
    sa.Column('classification_reason', sa.Text(), nullable=True),
    sa.Column('classified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_code', 'channel', 'external_message_id', name='uq_inbound_replies_external_message')
    )
    op.create_index(op.f('ix_inbound_replies_channel'), 'inbound_replies', ['channel'], unique=False)
    op.create_index(op.f('ix_inbound_replies_classified_at'), 'inbound_replies', ['classified_at'], unique=False)
    op.create_index(op.f('ix_inbound_replies_created_at'), 'inbound_replies', ['created_at'], unique=False)
    op.create_index(op.f('ix_inbound_replies_creator_id'), 'inbound_replies', ['creator_id'], unique=False)
    op.create_index(op.f('ix_inbound_replies_department_code'), 'inbound_replies', ['department_code'], unique=False)
    op.create_index(op.f('ix_inbound_replies_direction'), 'inbound_replies', ['direction'], unique=False)
    op.create_index(op.f('ix_inbound_replies_external_message_id'), 'inbound_replies', ['external_message_id'], unique=False)
    op.create_index(op.f('ix_inbound_replies_message_at'), 'inbound_replies', ['message_at'], unique=False)
    op.create_index(op.f('ix_inbound_replies_processing_status'), 'inbound_replies', ['processing_status'], unique=False)
    op.create_index(op.f('ix_inbound_replies_reply_category'), 'inbound_replies', ['reply_category'], unique=False)
    op.create_table('outreach_emails',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('department_code', sa.String(length=40), nullable=False),
    sa.Column('creator_id', sa.String(length=120), nullable=False),
    sa.Column('to_email', sa.String(length=320), nullable=True),
    sa.Column('from_email', sa.String(length=320), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outreach_emails_created_at'), 'outreach_emails', ['created_at'], unique=False)
    op.create_index(op.f('ix_outreach_emails_creator_id'), 'outreach_emails', ['creator_id'], unique=False)
    op.create_index(op.f('ix_outreach_emails_department_code'), 'outreach_emails', ['department_code'], unique=False)
    op.create_index(op.f('ix_outreach_emails_sent_at'), 'outreach_emails', ['sent_at'], unique=False)
    op.create_index(op.f('ix_outreach_emails_status'), 'outreach_emails', ['status'], unique=False)
    op.create_table('agent_followup_runs',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('department_code', sa.String(length=40), nullable=False),
    sa.Column('creator_id', sa.String(length=120), nullable=False),
    sa.Column('inbound_reply_id', sa.String(length=120), nullable=False),
    sa.Column('reply_category', sa.String(length=40), nullable=True),
    sa.Column('suggested_status', sa.String(length=80), nullable=True),
    sa.Column('llm_status', sa.String(length=40), nullable=False),
    sa.Column('block_reason', sa.String(length=80), nullable=True),
    sa.Column('execution_status', sa.String(length=40), nullable=False),
    sa.Column('claim_token', sa.String(length=120), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(), nullable=True),
    sa.Column('provider_model', sa.String(length=160), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('prompt_characters', sa.Integer(), nullable=True),
    sa.Column('output_characters', sa.Integer(), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('context_json', sa.Text(), nullable=True),
    sa.Column('output_json', sa.Text(), nullable=True),
    sa.Column('validation_error', sa.Text(), nullable=True),
    sa.Column('prompt_version', sa.String(length=80), nullable=True),
    sa.Column('rendered_prompt', sa.Text(), nullable=True),
    sa.Column('reference_materials_json', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.ForeignKeyConstraint(['inbound_reply_id'], ['inbound_replies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_followup_runs_block_reason'), 'agent_followup_runs', ['block_reason'], unique=False)
    op.create_index(op.f('ix_agent_followup_runs_claim_token'), 'agent_followup_runs', ['claim_token'], unique=False)
    op.create_index(op.f('ix_agent_followup_runs_created_at'), 'agent_followup_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_followup_runs_creator_id'), 'agent_followup_runs', ['creator_id'], unique=False)
    op.create_index('ix_agent_followup_runs_creator_reply', 'agent_followup_runs', ['creator_id', 'inbound_reply_id'], unique=False)
    op.create_index(op.f('ix_agent_followup_runs_department_code'), 'agent_followup_runs', ['department_code'], unique=False)
    op.create_index('ix_agent_followup_runs_department_created', 'agent_followup_runs', ['department_code', 'created_at'], unique=False)
    op.create_index('ix_agent_followup_runs_execution_created', 'agent_followup_runs', ['execution_status', 'created_at'], unique=False)
    op.create_index('ix_agent_followup_runs_execution_lease', 'agent_followup_runs', ['execution_status', 'lease_expires_at'], unique=False)
    op.create_index(op.f('ix_agent_followup_runs_execution_status'), 'agent_followup_runs', ['execution_status'], unique=False)
    op.create_index(op.f('ix_agent_followup_runs_finished_at'), 'agent_followup_runs', ['finished_at'], unique=False)
    op.create_index(op.f('ix_agent_followup_runs_inbound_reply_id'), 'agent_followup_runs', ['inbound_reply_id'], unique=False)
    op.create_index(op.f('ix_agent_followup_runs_lease_expires_at'), 'agent_followup_runs', ['lease_expires_at'], unique=False)
    op.create_index(op.f('ix_agent_followup_runs_llm_status'), 'agent_followup_runs', ['llm_status'], unique=False)
    op.create_index(op.f('ix_agent_followup_runs_prompt_version'), 'agent_followup_runs', ['prompt_version'], unique=False)
    op.create_index(op.f('ix_agent_followup_runs_reply_category'), 'agent_followup_runs', ['reply_category'], unique=False)
    op.create_index(op.f('ix_agent_followup_runs_started_at'), 'agent_followup_runs', ['started_at'], unique=False)
    op.create_index(op.f('ix_agent_followup_runs_suggested_status'), 'agent_followup_runs', ['suggested_status'], unique=False)
    op.create_index('uq_agent_followup_runs_active_reply', 'agent_followup_runs', ['inbound_reply_id'], unique=True, postgresql_where=sa.text("execution_status IN ('queued', 'running')"), sqlite_where=sa.text("execution_status IN ('queued', 'running')"))
    op.create_table('do_not_contact_confirmations',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('department_code', sa.String(length=40), nullable=False),
    sa.Column('creator_id', sa.String(length=120), nullable=False),
    sa.Column('inbound_reply_id', sa.String(length=120), nullable=False),
    sa.Column('reason', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('reviewed_by', sa.String(length=120), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.ForeignKeyConstraint(['inbound_reply_id'], ['inbound_replies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dnc_confirmations_creator_status', 'do_not_contact_confirmations', ['creator_id', 'status'], unique=False)
    op.create_index(op.f('ix_do_not_contact_confirmations_created_at'), 'do_not_contact_confirmations', ['created_at'], unique=False)
    op.create_index(op.f('ix_do_not_contact_confirmations_creator_id'), 'do_not_contact_confirmations', ['creator_id'], unique=False)
    op.create_index(op.f('ix_do_not_contact_confirmations_department_code'), 'do_not_contact_confirmations', ['department_code'], unique=False)
    op.create_index(op.f('ix_do_not_contact_confirmations_inbound_reply_id'), 'do_not_contact_confirmations', ['inbound_reply_id'], unique=False)
    op.create_table('simulated_outbound_instructions',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('creator_id', sa.String(length=120), nullable=False),
    sa.Column('inbound_reply_id', sa.String(length=120), nullable=False),
    sa.Column('action_type', sa.String(length=60), nullable=False),
    sa.Column('template_key', sa.String(length=80), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.ForeignKeyConstraint(['inbound_reply_id'], ['inbound_replies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inbound_reply_id', 'action_type', name='uq_outbound_instruction_reply_action')
    )
    op.create_index(op.f('ix_simulated_outbound_instructions_action_type'), 'simulated_outbound_instructions', ['action_type'], unique=False)
    op.create_index(op.f('ix_simulated_outbound_instructions_created_at'), 'simulated_outbound_instructions', ['created_at'], unique=False)
    op.create_index(op.f('ix_simulated_outbound_instructions_creator_id'), 'simulated_outbound_instructions', ['creator_id'], unique=False)
    op.create_index(op.f('ix_simulated_outbound_instructions_inbound_reply_id'), 'simulated_outbound_instructions', ['inbound_reply_id'], unique=False)
    op.create_index(op.f('ix_simulated_outbound_instructions_status'), 'simulated_outbound_instructions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_simulated_outbound_instructions_status'), table_name='simulated_outbound_instructions')
    op.drop_index(op.f('ix_simulated_outbound_instructions_inbound_reply_id'), table_name='simulated_outbound_instructions')
    op.drop_index(op.f('ix_simulated_outbound_instructions_creator_id'), table_name='simulated_outbound_instructions')
    op.drop_index(op.f('ix_simulated_outbound_instructions_created_at'), table_name='simulated_outbound_instructions')
    op.drop_index(op.f('ix_simulated_outbound_instructions_action_type'), table_name='simulated_outbound_instructions')
    op.drop_table('simulated_outbound_instructions')
    op.drop_index(op.f('ix_do_not_contact_confirmations_inbound_reply_id'), table_name='do_not_contact_confirmations')
    op.drop_index(op.f('ix_do_not_contact_confirmations_department_code'), table_name='do_not_contact_confirmations')
    op.drop_index(op.f('ix_do_not_contact_confirmations_creator_id'), table_name='do_not_contact_confirmations')
    op.drop_index(op.f('ix_do_not_contact_confirmations_created_at'), table_name='do_not_contact_confirmations')
    op.drop_index('ix_dnc_confirmations_creator_status', table_name='do_not_contact_confirmations')
    op.drop_table('do_not_contact_confirmations')
    op.drop_index('uq_agent_followup_runs_active_reply', table_name='agent_followup_runs', postgresql_where=sa.text("execution_status IN ('queued', 'running')"), sqlite_where=sa.text("execution_status IN ('queued', 'running')"))
    op.drop_index(op.f('ix_agent_followup_runs_suggested_status'), table_name='agent_followup_runs')
    op.drop_index(op.f('ix_agent_followup_runs_started_at'), table_name='agent_followup_runs')
    op.drop_index(op.f('ix_agent_followup_runs_reply_category'), table_name='agent_followup_runs')
    op.drop_index(op.f('ix_agent_followup_runs_prompt_version'), table_name='agent_followup_runs')
    op.drop_index(op.f('ix_agent_followup_runs_llm_status'), table_name='agent_followup_runs')
    op.drop_index(op.f('ix_agent_followup_runs_lease_expires_at'), table_name='agent_followup_runs')
    op.drop_index(op.f('ix_agent_followup_runs_inbound_reply_id'), table_name='agent_followup_runs')
    op.drop_index(op.f('ix_agent_followup_runs_finished_at'), table_name='agent_followup_runs')
    op.drop_index(op.f('ix_agent_followup_runs_execution_status'), table_name='agent_followup_runs')
    op.drop_index('ix_agent_followup_runs_execution_lease', table_name='agent_followup_runs')
    op.drop_index('ix_agent_followup_runs_execution_created', table_name='agent_followup_runs')
    op.drop_index('ix_agent_followup_runs_department_created', table_name='agent_followup_runs')
    op.drop_index(op.f('ix_agent_followup_runs_department_code'), table_name='agent_followup_runs')
    op.drop_index('ix_agent_followup_runs_creator_reply', table_name='agent_followup_runs')
    op.drop_index(op.f('ix_agent_followup_runs_creator_id'), table_name='agent_followup_runs')
    op.drop_index(op.f('ix_agent_followup_runs_created_at'), table_name='agent_followup_runs')
    op.drop_index(op.f('ix_agent_followup_runs_claim_token'), table_name='agent_followup_runs')
    op.drop_index(op.f('ix_agent_followup_runs_block_reason'), table_name='agent_followup_runs')
    op.drop_table('agent_followup_runs')
    op.drop_index(op.f('ix_outreach_emails_status'), table_name='outreach_emails')
    op.drop_index(op.f('ix_outreach_emails_sent_at'), table_name='outreach_emails')
    op.drop_index(op.f('ix_outreach_emails_department_code'), table_name='outreach_emails')
    op.drop_index(op.f('ix_outreach_emails_creator_id'), table_name='outreach_emails')
    op.drop_index(op.f('ix_outreach_emails_created_at'), table_name='outreach_emails')
    op.drop_table('outreach_emails')
    op.drop_index(op.f('ix_inbound_replies_reply_category'), table_name='inbound_replies')
    op.drop_index(op.f('ix_inbound_replies_processing_status'), table_name='inbound_replies')
    op.drop_index(op.f('ix_inbound_replies_message_at'), table_name='inbound_replies')
    op.drop_index(op.f('ix_inbound_replies_external_message_id'), table_name='inbound_replies')
    op.drop_index(op.f('ix_inbound_replies_direction'), table_name='inbound_replies')
    op.drop_index(op.f('ix_inbound_replies_department_code'), table_name='inbound_replies')
    op.drop_index(op.f('ix_inbound_replies_creator_id'), table_name='inbound_replies')
    op.drop_index(op.f('ix_inbound_replies_created_at'), table_name='inbound_replies')
    op.drop_index(op.f('ix_inbound_replies_classified_at'), table_name='inbound_replies')
    op.drop_index(op.f('ix_inbound_replies_channel'), table_name='inbound_replies')
    op.drop_table('inbound_replies')
    op.drop_index(op.f('ix_followup_tasks_task_type'), table_name='followup_tasks')
    op.drop_index(op.f('ix_followup_tasks_status'), table_name='followup_tasks')
    op.drop_index(op.f('ix_followup_tasks_department_code'), table_name='followup_tasks')
    op.drop_index(op.f('ix_followup_tasks_creator_id'), table_name='followup_tasks')
    op.drop_index(op.f('ix_followup_tasks_created_at'), table_name='followup_tasks')
    op.drop_table('followup_tasks')
    op.drop_index(op.f('ix_creator_outreach_events_event_type'), table_name='creator_outreach_events')
    op.drop_index(op.f('ix_creator_outreach_events_event_at'), table_name='creator_outreach_events')
    op.drop_index(op.f('ix_creator_outreach_events_department_code'), table_name='creator_outreach_events')
    op.drop_index(op.f('ix_creator_outreach_events_creator_id'), table_name='creator_outreach_events')
    op.drop_index(op.f('ix_creator_outreach_events_created_at'), table_name='creator_outreach_events')
    op.drop_table('creator_outreach_events')
    op.drop_index(op.f('ix_reference_materials_scope'), table_name='reference_materials')
    op.drop_index(op.f('ix_reference_materials_reference_key'), table_name='reference_materials')
    op.drop_index(op.f('ix_reference_materials_product_type'), table_name='reference_materials')
    op.drop_index(op.f('ix_reference_materials_material_type'), table_name='reference_materials')
    op.drop_index(op.f('ix_reference_materials_is_active'), table_name='reference_materials')
    op.drop_index(op.f('ix_reference_materials_created_at'), table_name='reference_materials')
    op.drop_index('ix_reference_materials_active_scope_product', table_name='reference_materials')
    op.drop_table('reference_materials')
    op.drop_index(op.f('ix_products_product_type'), table_name='products')
    op.drop_index(op.f('ix_products_is_active'), table_name='products')
    op.drop_index(op.f('ix_products_created_at'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_creators_platform'), table_name='creators')
    op.drop_index(op.f('ix_creators_owner_bd'), table_name='creators')
    op.drop_index(op.f('ix_creators_handle'), table_name='creators')
    op.drop_index(op.f('ix_creators_followers_count'), table_name='creators')
    op.drop_index(op.f('ix_creators_email'), table_name='creators')
    op.drop_index(op.f('ix_creators_do_not_contact_status'), table_name='creators')
    op.drop_index(op.f('ix_creators_do_not_contact_requested_at'), table_name='creators')
    op.drop_index(op.f('ix_creators_department_code'), table_name='creators')
    op.drop_index(op.f('ix_creators_current_status'), table_name='creators')
    op.drop_index(op.f('ix_creators_created_at'), table_name='creators')
    op.drop_table('creators')
    # ### end Alembic commands ###
